// [clue, answer, wrong1, wrong2, wrong3]
export type Fact = [string, string, string, string, string];

export const cricket: Record<number, Fact[]> = {
  1: [
    ['How many players in one cricket team?', '11', '9', '10', '12'],
    ['What do you hit the ball with in cricket?', 'Bat', 'Racket', 'Stick', 'Club'],
    ['What is the ball made of in cricket?', 'Leather', 'Rubber', 'Plastic', 'Wood'],
    ['What shape is a cricket ground?', 'Oval', 'Square', 'Rectangle', 'Triangle'],
    ['What are the three sticks behind the batter called?', 'Stumps', 'Poles', 'Posts', 'Rods'],
    ['What sits on top of the stumps?', 'Bails', 'Caps', 'Lids', 'Tops'],
    ['What do you call the person who throws the ball?', 'Bowler', 'Pitcher', 'Thrower', 'Server'],
    ['What do you call the person who catches the ball?', 'Fielder', 'Catcher', 'Keeper', 'Guard'],
    ['How many stumps are there at each end?', '3', '2', '4', '5'],
    ['What colour clothes do players wear in Test cricket?', 'White', 'Blue', 'Green', 'Red'],
    ['What is the area in the middle of the ground called?', 'Pitch', 'Court', 'Track', 'Lane'],
    ['What does the umpire raise for a six?', 'Both hands', 'One hand', 'A flag', 'A hat'],
    ['How many runs do you get for hitting over the boundary?', '6', '4', '5', '3'],
    ['What is it called when the ball rolls to the boundary?', 'Four', 'Six', 'Three', 'Two'],
    ['Who stands behind the stumps with gloves?', 'Wicketkeeper', 'Goalkeeper', 'Catcher', 'Guard'],
    ['What do batters wear on their heads?', 'Helmet', 'Cap', 'Hat', 'Turban'],
    ['What do batters wear on their hands?', 'Gloves', 'Mittens', 'Wraps', 'Bands'],
    ['What do batters wear on their legs?', 'Pads', 'Shields', 'Guards', 'Wraps'],
    ['What happens when 10 batters are out?', 'Innings over', 'Game over', 'Break time', 'Extra turn'],
    ['What is it called when a batter scores zero?', 'Duck', 'Goose', 'Zero', 'Blank'],
    ['What colour is the ball in Test cricket?', 'Red', 'White', 'Pink', 'Yellow'],
    ['What does LBW stand for?', 'Leg Before Wicket', 'Left Ball Wide', 'Long Bat Wins', 'Low Ball Win'],
    ['Who decides if a batter is out?', 'Umpire', 'Coach', 'Captain', 'Crowd'],
    ['How many umpires are on the field?', '2', '1', '3', '4'],
    ['What does a batter do when the ball comes?', 'Hit it', 'Kick it', 'Catch it', 'Throw it'],
    ['Where does the bowler run from?', 'End of the pitch', 'Middle', 'Boundary', 'Side'],
    ['What is a cricket match played on?', 'Grass', 'Sand', 'Clay', 'Ice'],
    ['Which country invented cricket?', 'England', 'Australia', 'India', 'Pakistan'],
    ['What do you call a perfect throw hitting the stumps?', 'Run out', 'Home run', 'Strike out', 'Goal'],
    ['How many innings does each team get in a T20?', '1', '2', '3', '4'],
    ['What do teams do at the start of a match?', 'Toss a coin', 'Roll dice', 'Draw straws', 'Arm wrestle'],
    ['What does the winning captain choose after the toss?', 'Bat or bowl', 'Pitch side', 'Ball colour', 'Team size'],
    ['What is a wide ball?', 'Too far from batter', 'Too fast', 'Too slow', 'Too high'],
    ['What is a no ball?', 'Illegal delivery', 'Missed ball', 'Dropped ball', 'Lost ball'],
    ['How many runs is a wide worth?', '1', '0', '2', '3'],
    ['What colour is the ball in ODI cricket?', 'White', 'Red', 'Pink', 'Orange'],
    ['What is the longest format of cricket?', 'Test match', 'ODI', 'T20', 'T10'],
    ['How many days can a Test match last?', '5', '3', '7', '1'],
    ['What animal is on the Australian cricket logo?', 'Kangaroo', 'Koala', 'Emu', 'Platypus'],
    ['What is the ICC?', 'Cricket governing body', 'A TV channel', 'A team', 'A stadium'],
    ['Where is the home of cricket in England?', "Lord's", 'Wembley', 'Old Trafford', 'The Oval'],
    ['What is the crease line for?', 'Batter stands behind it', 'Bowler aim mark', 'Boundary line', 'Drinks break'],
    ['Which sport uses a bat, ball, and stumps?', 'Cricket', 'Baseball', 'Tennis', 'Golf'],
    ['What does "howzat" mean in cricket?', 'How is that (appeal)', 'Great shot', 'Bad ball', 'Nice catch'],
    ['What shape is a cricket bat?', 'Flat front, curved back', 'Round', 'Square', 'Triangular'],
    ['Which team bats first after winning the toss (if chosen)?', 'Batting team', 'Bowling team', 'Both teams', 'Neither'],
    ['What is the strip in the middle of the field?', 'Pitch', 'Lane', 'Path', 'Track'],
    ['What happens if you catch the ball after it is hit?', 'Batter is out', 'Free run', 'Extra ball', 'No result'],
    ['How is a batter "stumped"?', 'Keeper hits stumps when batter is out of crease', 'Ball hits head', 'Bat breaks', 'Ball is lost'],
    ['What is an "over" in cricket?', '6 balls bowled', '10 balls bowled', '5 balls bowled', '8 balls bowled'],
  ],
  2: [
    ['How many balls are in one over?', '6', '5', '8', '4'],
    ['How many overs in a T20 innings?', '20', '10', '50', '30'],
    ['How many overs in an ODI innings?', '50', '20', '40', '60'],
    ['What is a century in cricket?', '100 runs by one batter', '100 wickets', '100 overs', '100 catches'],
    ['What is a half-century?', '50 runs by one batter', '50 overs', '50 wickets', '50 catches'],
    ['What is a hat-trick in cricket?', '3 wickets in 3 balls', '3 sixes in a row', '3 catches', '3 run outs'],
    ['Which team wears green in international cricket?', 'Pakistan', 'India', 'England', 'Australia'],
    ['Which team wears blue in international cricket?', 'India', 'Pakistan', 'Sri Lanka', 'Bangladesh'],
    ['Which team wears yellow in international cricket?', 'Australia', 'England', 'South Africa', 'New Zealand'],
    ['What is a maiden over?', 'An over with no runs scored', 'First over of the match', 'Last over', 'Fastest over'],
    ['What is the boundary rope for?', 'Marks the edge of the field', 'Keeps players in', 'Decoration', 'Holds the net'],
    ['What is a yorker?', 'Ball aimed at the batters feet', 'A high bounce ball', 'Slow ball', 'Spin ball'],
    ['What is a bouncer?', 'Short ball that rises high', 'Ball that bounces twice', 'Wide ball', 'Fast full ball'],
    ['Who opens the batting?', 'Opening batters', 'Captain only', 'Wicketkeeper', 'Bowlers'],
    ['What does "retired hurt" mean?', 'Batter leaves due to injury', 'Batter is out', 'Game is paused', 'Ball is dead'],
    ['Where is the Melbourne Cricket Ground?', 'Australia', 'England', 'South Africa', 'India'],
    ['What is the Ashes series between?', 'England and Australia', 'India and Pakistan', 'NZ and SA', 'WI and SL'],
    ['What does "not out" mean?', 'Batter is still batting', 'Match is drawn', 'Rain stopped play', 'Over is finished'],
    ['What does "all out" mean?', '10 batters dismissed', 'All overs bowled', 'Everyone fielding', 'Match ended'],
    ['What is a spin bowler?', 'Bowler who turns the ball', 'Fast bowler', 'Left-handed bowler', 'Underarm bowler'],
    ['What is a fast bowler?', 'Bowler who bowls at high speed', 'Spin bowler', 'Slow bowler', 'Medium bowler'],
    ['What does DRS stand for?', 'Decision Review System', 'Direct Run Scoring', 'Digital Replay Screen', 'Double Run System'],
    ['What is the third umpire?', 'Off-field umpire using TV replays', 'A spare umpire', 'The coach', 'A referee'],
    ['What colour cap does the Australian Test team wear?', 'Baggy green', 'Yellow', 'White', 'Blue'],
    ['What is a "golden duck"?', 'Out on the first ball faced', 'Scoring 100 runs', 'Bowling 10 wickets', 'Winning the toss'],
    ['Which country hosted the first Cricket World Cup?', 'England', 'Australia', 'India', 'West Indies'],
    ['What year was the first Cricket World Cup?', '1975', '1983', '1992', '1970'],
    ['What is "bowling an over" mean?', 'Bowling 6 legal deliveries', 'Throwing the ball once', 'Spinning the ball', 'Fast bowling'],
    ['What do fielders try to do?', 'Catch or stop the ball', 'Hit the ball', 'Bowl the ball', 'Bat the ball'],
    ['What is a "slip" fielder?', 'Fielder next to the keeper', 'Fielder at boundary', 'Bowler', 'Batter'],
    ['What is the "powerplay" in limited-overs cricket?', 'Fielding restrictions period', 'Extra batting time', 'Bonus runs', 'Timeout'],
    ['What does "run rate" mean?', 'Average runs per over', 'Speed of bowler', 'Fielding speed', 'Pitch condition'],
    ['What is the highest score in a T20 innings?', 'Over 260', 'Over 400', 'Over 100', 'Over 500'],
    ['Who keeps the official score?', 'Scorer', 'Umpire', 'Captain', 'Coach'],
    ['What does "extras" mean in cricket?', 'Runs not scored by batter', 'Extra players', 'Bonus time', 'Additional overs'],
    ['Which country has a star on their cricket cap?', 'Pakistan', 'India', 'England', 'Australia'],
    ['What is a "nightwatchman"?', 'Lower-order batter sent in late', 'Security guard', 'Night umpire', 'Last bowler'],
    ['What is "tea" in a Test match?', 'A break between sessions', 'A drink on field', 'End of match', 'Award ceremony'],
    ['How many sessions in a day of Test cricket?', '3', '2', '4', '1'],
    ['What does "declaration" mean in cricket?', 'Team ends their innings voluntarily', 'Umpire ends game', 'Player retires', 'New ball request'],
    ['What is a "bye" in cricket?', 'Run when ball passes everyone', 'Goodbye to batter', 'Ball out of play', 'Free hit'],
    ['What is a "leg bye"?', 'Run when ball hits batter body', 'Leg injury', 'Batter runs fast', 'LBW appeal'],
    ['What colour ball is used in day-night Tests?', 'Pink', 'White', 'Red', 'Orange'],
    ['What does "follow-on" mean?', 'Team bats again immediately', 'Team bowls again', 'Extra innings', 'Bonus over'],
    ['What is a "free hit"?', 'Batter cannot be bowled out next ball', 'Free entry', 'Extra run', 'No ball'],
    ['Which trophy is for India vs Australia Tests?', 'Border-Gavaskar Trophy', 'The Ashes', 'Wisden Trophy', 'Frank Worrell Trophy'],
    ['What is a "dolly catch"?', 'Very easy catch', 'Hard catch', 'One-handed catch', 'Diving catch'],
    ['What is the "non-striker" end?', 'End where batter not facing', 'Bowling end', 'Fielding spot', 'Boundary'],
    ['What does "mankad" refer to?', 'Running out non-striker at bowling end', 'A batting shot', 'Bowling style', 'Fielding position'],
    ['Who tosses the coin before a match?', 'Both captains', 'Umpire', 'Coach', 'Match referee'],
  ],
  3: [
    ['What is the highest individual Test score ever?', '400 not out', '375', '365', '380'],
    ['Who scored 400 not out in Tests?', 'Brian Lara', 'Sachin Tendulkar', 'Don Bradman', 'Ricky Ponting'],
    ['What is Don Bradman\'s Test batting average?', '99.94', '95.50', '102.00', '89.78'],
    ['Which country won the first Cricket World Cup in 1975?', 'West Indies', 'England', 'Australia', 'India'],
    ['Which country won the 1983 Cricket World Cup?', 'India', 'West Indies', 'England', 'Pakistan'],
    ['Who captained India to the 1983 World Cup win?', 'Kapil Dev', 'Sunil Gavaskar', 'Imran Khan', 'Ravi Shastri'],
    ['What is a "googly"?', 'Leg-spinner\'s off-spin delivery', 'Fast ball', 'Slow bouncer', 'Yorker'],
    ['What is a "doosra"?', 'Off-spinner\'s leg-spin delivery', 'Fast yorker', 'Slow bouncer', 'Inswinger'],
    ['What is an "inswinger"?', 'Ball that curves into the batter', 'Ball curving away', 'Spinning ball', 'Bouncer'],
    ['What is an "outswinger"?', 'Ball that curves away from batter', 'Ball curving in', 'Spinning ball', 'Yorker'],
    ['Which Pakistani bowler was called "Sultan of Swing"?', 'Wasim Akram', 'Waqar Younis', 'Shoaib Akhtar', 'Imran Khan'],
    ['What is the fastest ball ever bowled in cricket?', '161.3 km/h', '155 km/h', '170 km/h', '150 km/h'],
    ['Who bowled the fastest ball in cricket history?', 'Shoaib Akhtar', 'Brett Lee', 'Mitchell Starc', 'Jeff Thomson'],
    ['What is a "reverse swing"?', 'Old ball swinging opposite way', 'New ball swing', 'Spin bowling', 'Slow bowling'],
    ['How many World Cups has Australia won (men\'s ODI)?', '6', '4', '5', '3'],
    ['What is the Duckworth-Lewis method used for?', 'Revised targets in rain-affected games', 'Deciding tie-breakers', 'Player rankings', 'Scoring extras'],
    ['Which ground is known as the "Mecca of Cricket"?', "Lord's", 'MCG', 'Eden Gardens', 'The Oval'],
    ['What is a "nightwatchman" used for in Test cricket?', 'Protect top-order late in the day', 'Bowl at night', 'Guard the stumps', 'Field at boundary'],
    ['Which player is known as the "Little Master"?', 'Sachin Tendulkar', 'Brian Lara', 'Ricky Ponting', 'Virat Kohli'],
    ['Who has the most Test wickets for Pakistan?', 'Wasim Akram', 'Waqar Younis', 'Imran Khan', 'Shoaib Akhtar'],
    ['What is "sledging" in cricket?', 'Verbal intimidation of opponents', 'Sliding fielding', 'Fast bowling', 'Aggressive batting'],
    ['Who has scored the most runs in ODI cricket?', 'Sachin Tendulkar', 'Virat Kohli', 'Ricky Ponting', 'Kumar Sangakkara'],
    ['What is the highest team score in ODI cricket?', '481/6', '443/9', '438/9', '500/8'],
    ['Which team scored 481/6 in an ODI?', 'England', 'Australia', 'India', 'South Africa'],
    ['What is "Chinaman" bowling?', 'Left-arm wrist spin', 'Right-arm fast', 'Off spin', 'Medium pace'],
    ['How long is the pitch in cricket?', '22 yards', '20 yards', '24 yards', '18 yards'],
    ['What is the "popping crease"?', 'Line the batter must stay behind', 'Bowling mark', 'Boundary line', 'Centre line'],
    ['What does "bowling crease" mark?', 'Where the stumps are placed', 'Batter position', 'Fielding line', 'Boundary edge'],
    ['Which country plays at Eden Gardens?', 'India', 'England', 'Australia', 'South Africa'],
    ['What is the capacity of Melbourne Cricket Ground?', 'About 100,000', '50,000', '75,000', '120,000'],
    ['Who won the 1992 Cricket World Cup?', 'Pakistan', 'England', 'Australia', 'New Zealand'],
    ['Who captained Pakistan in the 1992 World Cup?', 'Imran Khan', 'Wasim Akram', 'Javed Miandad', 'Inzamam-ul-Haq'],
    ['What is a "cover drive"?', 'Batting shot through covers', 'Bowling technique', 'Fielding position', 'Running between wickets'],
    ['What is a "pull shot"?', 'Horizontal bat shot to short ball', 'Defensive shot', 'Sweep shot', 'Drive shot'],
    ['What is a "sweep shot"?', 'Playing ball on one knee to leg side', 'A fast bowl', 'Driving the ball', 'Cutting the ball'],
    ['Who has the most Test centuries?', 'Sachin Tendulkar', 'Ricky Ponting', 'Jacques Kallis', 'Kumar Sangakkara'],
    ['How many Test centuries did Sachin Tendulkar score?', '51', '45', '55', '48'],
    ['What is the "Gabba" ground located in?', 'Brisbane', 'Sydney', 'Melbourne', 'Perth'],
    ['Which format of cricket is in the Olympics from 2028?', 'T20', 'ODI', 'Test', 'T10'],
    ['What does "super over" decide?', 'Tie-breaker in limited-overs', 'Bonus runs', 'Extra wickets', 'Player of match'],
    ['How many balls in a super over?', '6', '12', '3', '10'],
    ['Which country did Imran Khan play for?', 'Pakistan', 'India', 'England', 'Bangladesh'],
    ['What is a "leg cutter"?', 'Ball that cuts from leg to off', 'Batting shot', 'Fielding move', 'Running style'],
    ['What is an "off cutter"?', 'Ball that cuts from off to leg', 'Batting shot', 'Fielding move', 'Bowling warm-up'],
    ['What does "over rate" measure?', 'How fast overs are bowled per hour', 'Runs per over', 'Wickets per over', 'Catches per game'],
    ['What is the minimum over rate in Tests?', '15 overs per hour', '12 overs per hour', '20 overs per hour', '10 overs per hour'],
    ['Which trophy is for England vs West Indies Tests?', 'Wisden Trophy', 'The Ashes', 'Border-Gavaskar', 'Frank Worrell Trophy'],
    ['What is "bodyline" bowling?', 'Bowling at the batter\'s body', 'Bowling yorkers', 'Spin bowling', 'Slow bowling'],
    ['When did the Bodyline series happen?', '1932-33', '1948-49', '1956-57', '1970-71'],
    ['What colour jersey does England wear in ODIs?', 'Blue', 'White', 'Red', 'Green'],
  ],
  4: [
    ['Who has the most wickets in Test cricket history?', 'Muttiah Muralitharan', 'Shane Warne', 'Anil Kumble', 'James Anderson'],
    ['How many Test wickets did Muralitharan take?', '800', '708', '750', '619'],
    ['How many Test wickets did Shane Warne take?', '708', '800', '619', '563'],
    ['Who scored the first double century in ODIs?', 'Sachin Tendulkar', 'Rohit Sharma', 'Martin Guptill', 'Chris Gayle'],
    ['What was Sachin\'s ODI double century score?', '200 not out', '210', '215 not out', '190'],
    ['Which batsman has three ODI double centuries?', 'Rohit Sharma', 'Sachin Tendulkar', 'Chris Gayle', 'Virat Kohli'],
    ['Who is known as "Rawalpindi Express"?', 'Shoaib Akhtar', 'Wasim Akram', 'Waqar Younis', 'Mohammad Asif'],
    ['What is a "green top" pitch?', 'Grass-covered pitch aiding seamers', 'Dry spinning pitch', 'Flat batting pitch', 'Wet pitch'],
    ['What is a "dustbowl" pitch?', 'Dry pitch that helps spinners', 'Green seaming pitch', 'Flat batting track', 'Bouncy pitch'],
    ['Who has most ODI wickets for Pakistan?', 'Wasim Akram', 'Waqar Younis', 'Shahid Afridi', 'Shoaib Akhtar'],
    ['What is Wasim Akram\'s ODI wicket tally?', '502', '416', '450', '380'],
    ['Which bowler took 10 wickets in a Test innings?', 'Anil Kumble', 'Jim Laker', 'Muttiah Muralitharan', 'Shane Warne'],
    ['What were Kumble\'s figures in that innings?', '10/74', '10/90', '10/53', '10/110'],
    ['Against whom did Kumble take 10 wickets?', 'Pakistan', 'Australia', 'England', 'Sri Lanka'],
    ['Who is the "King of Swing" from Pakistan?', 'Wasim Akram', 'Imran Khan', 'Waqar Younis', 'Shoaib Akhtar'],
    ['What is the ICC Champions Trophy?', 'ODI tournament for top 8 teams', 'Test championship', 'T20 World Cup', 'Bilateral series'],
    ['Which team has won the most T20 World Cups?', 'West Indies', 'India', 'Australia', 'England'],
    ['How many T20 World Cups has West Indies won?', '2', '1', '3', '4'],
    ['Who hit six sixes in an over in international cricket?', 'Yuvraj Singh', 'Chris Gayle', 'Herschelle Gibbs', 'Shahid Afridi'],
    ['Against which bowler did Yuvraj hit six sixes?', 'Stuart Broad', 'Andrew Flintoff', 'James Anderson', 'Steve Harmison'],
    ['In which tournament did Yuvraj hit six sixes?', '2007 T20 World Cup', '2011 World Cup', '2003 World Cup', 'IPL 2008'],
    ['What is the IPL?', 'Indian Premier League (T20)', 'International Players League', 'Indian Players League', 'Indo-Pak League'],
    ['When was the first IPL season?', '2008', '2010', '2005', '2012'],
    ['What is the BBL in Australian cricket?', 'Big Bash League', 'Best Batters League', 'Bowling Bash League', 'Brisbane Ball League'],
    ['What is PSL in Pakistan cricket?', 'Pakistan Super League', 'Pakistan Sports League', 'Premier Super League', 'Punjab Super League'],
    ['What is the record for fastest T20I fifty?', '12 balls', '15 balls', '18 balls', '10 balls'],
    ['Who scored the fastest T20I century?', 'Rohit Sharma', 'Chris Gayle', 'David Miller', 'Aaron Finch'],
    ['What is a "Dilscoop" shot?', 'Flicking ball over the keeper', 'Reverse sweep', 'Switch hit', 'Helicopter shot'],
    ['Who invented the Dilscoop?', 'Tillakaratne Dilshan', 'Kumar Sangakkara', 'Mahela Jayawardene', 'Sanath Jayasuriya'],
    ['What is a "switch hit"?', 'Batter changes stance mid-delivery', 'Changing bowler', 'Swapping fielders', 'Switching ends'],
    ['Who is known for the "helicopter shot"?', 'MS Dhoni', 'Virat Kohli', 'Sachin Tendulkar', 'Rohit Sharma'],
    ['Which country does the "Barmy Army" support?', 'England', 'Australia', 'India', 'South Africa'],
    ['What is a "beamer" in cricket?', 'Full toss above waist height', 'Bouncer', 'Yorker', 'Slow ball'],
    ['Is a beamer legal in cricket?', 'No, it is illegal', 'Yes always', 'Only in T20s', 'Only in Tests'],
    ['What does "shoulder of the bat" mean?', 'Top edge of the bat blade', 'Handle part', 'Bottom of bat', 'Middle of bat'],
    ['Which Pakistani batter was known as "Boom Boom"?', 'Shahid Afridi', 'Inzamam-ul-Haq', 'Younis Khan', 'Mohammad Yousuf'],
    ['Which Indian batter is called "The Wall"?', 'Rahul Dravid', 'Sachin Tendulkar', 'VVS Laxman', 'Sourav Ganguly'],
    ['What is the "Kolkata miracle" of 2001?', 'India won after following on vs Australia', 'India won World Cup', 'India chased 400', 'India bowled out for 36'],
    ['Who scored 281 in the Kolkata 2001 Test?', 'VVS Laxman', 'Rahul Dravid', 'Sachin Tendulkar', 'Sourav Ganguly'],
    ['What does a "flat track bully" mean?', 'Batter who scores on easy pitches', 'Fast bowler', 'Aggressive fielder', 'Pitch curator'],
    ['What is a "corridor of uncertainty"?', 'Line outside off stump', 'Inside edge zone', 'Leg stump area', 'Middle stump line'],
    ['Which Australian captain was called "Punter"?', 'Ricky Ponting', 'Steve Waugh', 'Allan Border', 'Mark Taylor'],
    ['What is the "Wisden Cricketers\' Almanack"?', 'Annual cricket reference book', 'Cricket TV channel', 'Award ceremony', 'Cricket museum'],
    ['Since what year has the Wisden Almanack been published?', '1864', '1900', '1850', '1920'],
    ['Who won the 2019 ODI World Cup?', 'England', 'New Zealand', 'India', 'Australia'],
    ['How was the 2019 World Cup final decided?', 'Super over (boundary count)', 'Normal result', 'DLS method', 'Bowl-out'],
    ['Which ground hosted the 2019 World Cup final?', "Lord's", 'The Oval', 'Edgbaston', 'Old Trafford'],
    ['Who won the 2011 ODI World Cup?', 'India', 'Sri Lanka', 'Australia', 'Pakistan'],
    ['Who hit the winning six in the 2011 World Cup final?', 'MS Dhoni', 'Virat Kohli', 'Yuvraj Singh', 'Gautam Gambhir'],
    ['What is the "Mankading" rule now called by ICC?', 'Running out the non-striker', 'Unfair play', 'Dead ball', 'Penalty run'],
  ],
  5: [
    ['Who has the highest Test batting average (min 20 innings)?', 'Don Bradman', 'Sachin Tendulkar', 'Steve Smith', 'Virat Kohli'],
    ['What was Don Bradman\'s final Test innings score?', '0 (duck)', '4', '12', '50'],
    ['How many runs did Bradman need in his last innings for a 100 average?', '4', '10', '0', '6'],
    ['Who holds the record for most Test runs?', 'Sachin Tendulkar', 'Ricky Ponting', 'Jacques Kallis', 'Rahul Dravid'],
    ['How many Test runs did Sachin score?', '15,921', '13,378', '14,234', '12,472'],
    ['Who holds the record for most ODI runs?', 'Sachin Tendulkar', 'Virat Kohli', 'Ricky Ponting', 'Kumar Sangakkara'],
    ['How many ODI runs did Sachin score?', '18,426', '16,000', '17,500', '15,000'],
    ['Who has the most catches in Test history (non-keeper)?', 'Rahul Dravid', 'Ricky Ponting', 'Jacques Kallis', 'Mahela Jayawardene'],
    ['Which bowler has most Test wickets for Australia?', 'Shane Warne', 'Glenn McGrath', 'Dennis Lillee', 'Mitchell Johnson'],
    ['How many Test wickets did Glenn McGrath take?', '563', '519', '600', '480'],
    ['Which all-rounder has most Test runs and 300+ wickets?', 'Jacques Kallis', 'Imran Khan', 'Ian Botham', 'Kapil Dev'],
    ['What is Jacques Kallis\'s Test run tally?', '13,289', '11,000', '12,500', '10,000'],
    ['Who has the fastest five-wicket haul in Test cricket?', 'Stuart Broad', 'Mitchell Johnson', 'Dale Steyn', 'Wasim Akram'],
    ['Who has the highest individual T20I score?', 'Aaron Finch', 'Rohit Sharma', 'Chris Gayle', 'Colin Munro'],
    ['What was Aaron Finch\'s highest T20I score?', '172', '156', '162', '145'],
    ['What is the "Bazball" style of cricket?', 'Aggressive attacking Test play', 'Defensive bowling', 'Slow batting', 'Spin-only strategy'],
    ['Who coined the term "Bazball"?', 'Named after Brendon McCullum', 'Ben Stokes', 'Joe Root', 'Andrew Strauss'],
    ['Who is the youngest player to score a Test century?', 'Mohammad Ashraful', 'Sachin Tendulkar', 'Pat Cummins', 'Shahid Afridi'],
    ['What is the lowest Test team score ever?', '26', '30', '36', '42'],
    ['Which team was bowled out for 26 in a Test?', 'New Zealand', 'South Africa', 'England', 'Bangladesh'],
    ['Who has taken most wickets in a single World Cup?', 'Glenn McGrath', 'Mitchell Starc', 'Muttiah Muralitharan', 'Wasim Akram'],
    ['What is the "Super Over" format?', 'Each team bats 6 balls to break tie', 'Extra innings of 5 overs', 'Bowling competition', 'Coin toss'],
    ['Which team won the inaugural WTC final?', 'New Zealand', 'India', 'Australia', 'England'],
    ['What does WTC stand for?', 'World Test Championship', 'World Twenty20 Cup', 'World Trophy Cricket', 'Wisden Test Cup'],
    ['Who captained Australia to 16 consecutive Test wins?', 'Steve Waugh', 'Ricky Ponting', 'Allan Border', 'Mark Taylor'],
    ['What is the record for most consecutive Test wins?', '16', '12', '14', '10'],
    ['Who was the first batter to score 10,000 Test runs?', 'Sunil Gavaskar', 'Allan Border', 'Sachin Tendulkar', 'Brian Lara'],
    ['What is Virat Kohli\'s ODI century count (approx)?', '50', '43', '55', '38'],
    ['Who is the fastest to 8,000 ODI runs?', 'Virat Kohli', 'Sachin Tendulkar', 'AB de Villiers', 'Hashim Amla'],
    ['What is the highest partnership in Test cricket?', '624', '580', '550', '500'],
    ['Between which players was the 624-run stand?', 'Sangakkara and Jayawardene', 'Lara and Sarwan', 'Hayden and Langer', 'Tendulkar and Dravid'],
    ['Against which team was the 624-run stand?', 'South Africa', 'England', 'Australia', 'India'],
    ['Who has the most dismissals by a Test wicketkeeper?', 'Mark Boucher', 'Adam Gilchrist', 'MS Dhoni', 'Kumar Sangakkara'],
    ['How many Test dismissals did Mark Boucher have?', '555', '500', '472', '416'],
    ['Who was the first to take 600 Test wickets?', 'Shane Warne', 'Muttiah Muralitharan', 'Anil Kumble', 'Glenn McGrath'],
    ['What is the "Impact Player" rule in IPL?', 'Substitute player can bat and bowl', 'Extra fielder', 'Power hitter', 'Super sub bowler'],
    ['Which Pakistani bowler has most T20I wickets?', 'Shaheen Afridi', 'Shadab Khan', 'Mohammad Amir', 'Haris Rauf'],
    ['What is a "pink ball" Test?', 'Day-night Test with pink ball', 'Women\'s Test', 'Youth Test', 'Charity match'],
    ['Where was the first pink ball Test played?', 'Adelaide', 'Kolkata', 'Dubai', "Lord's"],
    ['In what year was the first pink ball Test?', '2015', '2017', '2019', '2013'],
    ['Who has the most runs in IPL history?', 'Virat Kohli', 'Suresh Raina', 'Rohit Sharma', 'David Warner'],
    ['Who has the most wickets in IPL history?', 'Yuzvendra Chahal', 'Dwayne Bravo', 'Lasith Malinga', 'Amit Mishra'],
    ['What is the "Powerplay" in T20 cricket?', 'First 6 overs with fielding restrictions', 'Last 5 overs', 'Middle 10 overs', 'First 4 overs'],
    ['How many fielders outside the circle during Powerplay?', '2', '4', '5', '3'],
    ['What is a "death bowler"?', 'Bowler who bowls at the end of innings', 'First over bowler', 'Spin bowler', 'Part-time bowler'],
    ['Which country hosted the 2023 ODI World Cup?', 'India', 'England', 'Australia', 'South Africa'],
    ['Who won the 2023 ODI World Cup?', 'Australia', 'India', 'England', 'South Africa'],
    ['What is a "review" in cricket?', 'Team challenges umpire decision via DRS', 'Watching highlights', 'Checking run rate', 'Reviewing team selection'],
    ['How many DRS reviews per innings in Tests?', '2', '1', '3', '4'],
    ['Who scored the fastest ODI century (off 31 balls)?', 'AB de Villiers', 'Shahid Afridi', 'Corey Anderson', 'Chris Gayle'],
  ],
  6: [
    ['What is the "Duckworth-Lewis-Stern" method factor?', 'Resources remaining (wickets and overs)', 'Team rankings', 'Ground size', 'Weather forecast'],
    ['Who developed the original DL method?', 'Frank Duckworth and Tony Lewis', 'ICC committee', 'Richie Benaud', 'Clive Lloyd'],
    ['What replaced the DL method?', 'DLS (Duckworth-Lewis-Stern)', 'VJD method', 'Average run rate', 'Net run rate'],
    ['What does "wagon wheel" show in cricket?', 'Direction of all shots by a batter', 'Fielding positions', 'Bowling speeds', 'Run rate graph'],
    ['What is "Hawkeye" used for in cricket?', 'Ball tracking for LBW decisions', 'Catching review', 'Boundary check', 'No-ball detection'],
    ['What does "Snickometer" detect?', 'Edge of bat via sound waves', 'Speed of ball', 'Spin rate', 'Bounce height'],
    ['What is "UltraEdge" in cricket?', 'Visual and sound edge detection', 'Fast ball tracker', 'Wicket animation', 'Pitch mapping'],
    ['Who has the best bowling average in Tests (min 200 wkts)?', 'Malcolm Marshall', 'Dale Steyn', 'Glenn McGrath', 'Curtly Ambrose'],
    ['What was Malcolm Marshall\'s Test average?', '20.94', '22.29', '21.64', '23.68'],
    ['What is the "Reliance ICC Rankings"?', 'Official player/team ranking system', 'Sponsorship deal', 'Tournament name', 'Broadcasting rights'],
    ['Who is the only player to score 100 international centuries?', 'Sachin Tendulkar', 'Virat Kohli', 'Ricky Ponting', 'Jacques Kallis'],
    ['What is the "Nelson" score superstition?', '111 is considered unlucky', '99 is unlucky', '13 is unlucky', '200 is unlucky'],
    ['What is a "minefield" in cricket?', 'Deteriorating pitch with uneven bounce', 'Fielding setup', 'Bowling strategy', 'Green pitch'],
    ['Who was the first to take a hat-trick in World Cup?', 'Chetan Sharma', 'Wasim Akram', 'Brett Lee', 'Lasith Malinga'],
    ['In what year did Chetan Sharma take WC hat-trick?', '1987', '1983', '1992', '1996'],
    ['Who took a hat-trick in a World Cup final?', 'No one has', 'Wasim Akram', 'Glenn McGrath', 'Shane Warne'],
    ['What is "batting collapse"?', 'Multiple wickets falling quickly', 'Slow scoring', 'Pitch damage', 'Injury break'],
    ['What does "net run rate" calculate?', 'Difference between run rates for and against', 'Total runs per match', 'Average score', 'Boundary percentage'],
    ['How is NRR used in tournaments?', 'Tie-breaker for teams on equal points', 'Seeding system', 'Prize money', 'Home advantage'],
    ['What is the "Spirit of Cricket" preamble?', 'Code of conduct in the Laws of Cricket', 'Opening ceremony', 'Toss ritual', 'Team anthem'],
    ['Who governs the Laws of Cricket?', 'MCC (Marylebone Cricket Club)', 'ICC', 'ECB', 'BCCI'],
    ['What is a "concussion substitute"?', 'Replacement for a concussed player', 'Extra fielder', 'Substitute umpire', 'Reserve bowler'],
    ['When were concussion substitutes introduced?', '2019', '2017', '2021', '2015'],
    ['What is the "Player of the Tournament" award?', 'Best performer across the tournament', 'Highest scorer', 'Most wickets', 'Best fielder'],
    ['What is "Kolpak" in cricket context?', 'EU ruling allowing foreign players as locals', 'Bowling style', 'Pitch type', 'Stadium name'],
    ['What does the "third man" field position mean?', 'Behind the keeper on off side near boundary', 'Third fielder', 'Substitute player', 'Reserve umpire'],
    ['What is "silly point"?', 'Very close fielding position on off side', 'A bad shot', 'Bowling mistake', 'Funny commentary'],
    ['What is "short leg" position?', 'Close fielder on leg side', 'Short run', 'Leg injury', 'Quick single'],
    ['Why is "leg before wicket" given out?', 'Ball would have hit stumps but hit pad', 'Batter moved too slow', 'Bat hit pad', 'Ball hit helmet'],
    ['What conditions must be met for LBW?', 'Ball pitching in line, hitting in line, hitting stumps', 'Just hitting pads', 'Ball bouncing twice', 'Batter not moving'],
    ['What is a "featherbed" pitch?', 'Very flat, easy batting surface', 'Wet pitch', 'Green pitch', 'Dusty pitch'],
    ['What is "declaration bowling"?', 'Easy bowling to speed up scoring for declaration', 'Fast bowling', 'Spin bowling', 'Death bowling'],
    ['What is the "follow-on" margin in Tests?', '200 runs', '150 runs', '250 runs', '100 runs'],
    ['What is the follow-on margin in a 3-day match?', '150 runs', '200 runs', '100 runs', '75 runs'],
    ['Who captained Australia\'s "Invincibles" tour of 1948?', 'Don Bradman', 'Richie Benaud', 'Bill Ponsford', 'Keith Miller'],
    ['Why were they called "Invincibles"?', 'Unbeaten on entire tour', 'Won the Ashes 5-0', 'Highest team score', 'Fastest win'],
    ['What is "Timeless Test"?', 'Test match with no time limit', 'Longest session', 'Day-night Test', 'Five-day Test'],
    ['When was the last Timeless Test played?', '1939', '1950', '1928', '1960'],
    ['What is the World Cricket League?', 'Tournament for associate ICC members', 'Main World Cup', 'T20 league', 'Women\'s tournament'],
    ['What does "associate member" mean in ICC?', 'Country developing cricket', 'Full member', 'Founding member', 'Suspended member'],
    ['What is the "Impact Index" in cricket analytics?', 'Measures player impact on match outcome', 'Batting average', 'Bowling economy', 'Fielding percentage'],
    ['What is a "par score" in DLS?', 'Target score at any point using DLS', 'Average ground score', 'Highest score', 'Minimum score'],
    ['Who has the most Test catches by a fielder?', 'Rahul Dravid', 'Ricky Ponting', 'Jacques Kallis', 'Mark Waugh'],
    ['What is "Bazball" coach Ben Stokes\' role?', 'England Test captain', 'Head coach', 'Bowling coach', 'Batting coach'],
    ['Who was appointed England men\'s Test coach in 2022?', 'Brendon McCullum', 'Gary Kirsten', 'Justin Langer', 'Jason Gillespie'],
    ['What is a "five-wicket haul" also called?', 'Five-for or fifer', 'Hat-trick', 'Maiden spell', 'Full house'],
    ['What is "rain rule" in cricket?', 'DLS revised target for rain delays', 'Match cancelled', 'Extra day added', 'Ground covers used'],
    ['Who has bowled the most maiden overs in Tests?', 'Glenn McGrath', 'Curtly Ambrose', 'Shane Warne', 'James Anderson'],
    ['What does "economy rate" measure for a bowler?', 'Average runs conceded per over', 'Wickets per match', 'Speed of delivery', 'Dot ball percentage'],
    ['What is the highest successful run chase in Tests?', '418 by West Indies', '387 by India', '404 by Australia', '369 by Sri Lanka'],
  ],
};

export const sports: Record<number, Fact[]> = {
  1: [
    ['How many players on a soccer team on the field?', '11', '9', '10', '12'],
    ['What sport do you play with a round orange ball?', 'Basketball', 'Football', 'Tennis', 'Golf'],
    ['What colour is a tennis ball?', 'Yellow-green', 'White', 'Orange', 'Red'],
    ['How many rings are on the Olympic flag?', '5', '3', '4', '6'],
    ['What sport does Dwayne "The Rock" Johnson come from?', 'WWE/Wrestling', 'Boxing', 'Football', 'MMA'],
    ['What do you hit in badminton?', 'Shuttlecock', 'Ball', 'Puck', 'Disc'],
    ['What do WWE wrestlers fight inside?', 'A ring', 'An octagon', 'A cage', 'A court'],
    ['In soccer, who can use their hands?', 'Goalkeeper', 'Striker', 'Midfielder', 'Defender'],
    ['What sport do Messi and Ronaldo play?', 'Football/Soccer', 'Tennis', 'Basketball', 'Rugby'],
    ['What sport is played with sticks and a ball on a grass field?', 'Field hockey', 'Tennis', 'Golf', 'Badminton'],
    ['What do you try to score in soccer?', 'Goal', 'Point', 'Basket', 'Run'],
    ['What do Formula 1 drivers race in?', 'Race cars', 'Motorcycles', 'Go-karts', 'Trucks'],
    ['How many holes are on a standard golf course?', '18', '9', '12', '15'],
    ['What do you throw in bowling?', 'Bowling ball', 'Pin', 'Disc', 'Stone'],
    ['What does WWE stand for?', 'World Wrestling Entertainment', 'World Wide Entertainment', 'Wrestling World Event', 'World Wrestling Exhibition'],
    ['Which sport uses a net and racket?', 'Tennis', 'Soccer', 'Swimming', 'Running'],
    ['What do runners run on at the Olympics?', 'Track', 'Road', 'Grass', 'Sand'],
    ['What sport do you ride a bicycle in?', 'Cycling', 'Swimming', 'Running', 'Rowing'],
    ['What do you kick in soccer?', 'Ball', 'Puck', 'Shuttlecock', 'Stone'],
    ['What do boxers wear on their hands?', 'Gloves', 'Mittens', 'Wraps', 'Nothing'],
    ['Where are the Olympics held?', 'Different country each time', 'Always in Greece', 'Always in USA', 'Always in France'],
    ['What is the most popular football league in England called?', 'Premier League', 'La Liga', 'Serie A', 'Bundesliga'],
    ['What do you do in a relay race?', 'Pass a baton', 'Kick a ball', 'Throw a disc', 'Hit a puck'],
    ['What animal is a race with horses called?', 'Horse racing', 'Dog racing', 'Cat racing', 'Bird racing'],
    ['What sport is played by hitting a small ball against a wall with a racket?', 'Squash', 'Tennis', 'Badminton', 'Table tennis'],
    ['What colour belt is highest in karate?', 'Black', 'White', 'Red', 'Yellow'],
    ['In which team sport do players tag opponents while chanting "kabaddi"?', 'Kabaddi', 'Rugby', 'Wrestling', 'Handball'],
    ['How many players on a basketball team on court?', '5', '6', '7', '4'],
    ['What do you score through in basketball?', 'Hoop/basket', 'Goal', 'Net', 'Ring'],
    ['What does a WWE referee count to for a pinfall?', '3', '5', '10', '7'],
    ['Which boxer was known as "The Greatest"?', 'Muhammad Ali', 'Mike Tyson', 'Floyd Mayweather', 'Manny Pacquiao'],
    ['What sport uses a white ball with dimples?', 'Golf', 'Tennis', 'Cricket', 'Baseball'],
    ['What do you call the person who runs a race?', 'Runner', 'Swimmer', 'Rider', 'Player'],
    ['What sport is Michael Phelps famous for?', 'Swimming', 'Running', 'Cycling', 'Gymnastics'],
    ['What sport is Usain Bolt famous for?', 'Sprinting', 'Swimming', 'Jumping', 'Throwing'],
    ['What do you wear to protect your head in cycling?', 'Helmet', 'Hat', 'Cap', 'Headband'],
    ['How many goals does a soccer net have on each end?', '1', '2', '3', '0'],
    ['What colour shirt does the Brazil football team wear?', 'Yellow', 'Blue', 'Green', 'White'],
    ['How many players are on a field hockey team?', '11', '9', '10', '12'],
    ['What NBA team plays in Toronto?', 'Raptors', 'Lakers', 'Celtics', 'Bulls'],
    ['What shape is the UFC fighting area?', 'Octagon', 'Circle', 'Square', 'Rectangle'],
    ['What is the most popular sport in Canada?', 'Ice hockey', 'Basketball', 'Soccer', 'Baseball'],
    ['Who is John Cena famous as?', 'WWE wrestler', 'Boxer', 'Football player', 'MMA fighter'],
    ['What sport is played with a heavy ball and pins?', 'Bowling', 'Cricket', 'Golf', 'Tennis'],
    ['What do tennis players hit the ball over?', 'Net', 'Wall', 'Fence', 'Rope'],
    ['In which sport do athletes jump over hurdles?', 'Track and field', 'Swimming', 'Cycling', 'Tennis'],
    ['What is the Olympic motto?', 'Faster, Higher, Stronger', 'Win at all costs', 'Be the best', 'Play fair'],
    ['Where were the ancient Olympics held?', 'Greece', 'Rome', 'Egypt', 'China'],
    ['What do you hit a golf ball with?', 'Golf club', 'Bat', 'Racket', 'Stick'],
    ['What is a marathon?', 'A very long running race', 'Short sprint', 'Swimming race', 'Cycling race'],
  ],
  2: [
    ['How long is an Olympic swimming pool?', '50 meters', '25 meters', '100 meters', '75 meters'],
    ['What country is soccer called "football" in?', 'Most countries', 'Only USA', 'Only Canada', 'Only Australia'],
    ['Which sport has a slam dunk?', 'Basketball', 'Tennis', 'Volleyball', 'Soccer'],
    ['What are the five Olympic ring colours?', 'Blue, yellow, black, green, red', 'Red, white, blue, green, gold', 'All rainbow', 'Red, blue, green, yellow, white'],
    ['How often are the Summer Olympics held?', 'Every 4 years', 'Every 2 years', 'Every year', 'Every 5 years'],
    ['What is the Tour de France?', 'Famous cycling race', 'Running race', 'Car race', 'Swimming race'],
    ['What is the biggest WWE event of the year called?', 'WrestleMania', 'Royal Rumble', 'SummerSlam', 'Survivor Series'],
    ['What is a "derby" in football?', 'A match between local rivals', 'A cup final', 'A friendly match', 'A league opener'],
    ['In which Olympic sport has Pakistan won the most gold medals?', 'Field hockey', 'Cricket', 'Squash', 'Wrestling'],
    ['What is the World Cup in soccer?', 'Global tournament every 4 years', 'Weekly league', 'Annual cup', 'Monthly match'],
    ['Which animal is on the Ferrari F1 logo?', 'Horse', 'Bull', 'Eagle', 'Lion'],
    ['What is The Undertaker\'s nickname in WWE?', 'The Deadman', 'The Animal', 'The Viper', 'The Beast'],
    ['How does a Formula 1 race start?', 'Lights go out', 'A flag drops', 'A horn sounds', 'A whistle blows'],
    ['What sport is Serena Williams famous for?', 'Tennis', 'Swimming', 'Golf', 'Running'],
    ['How many sets does a tennis player need to win (men\'s)?', '3 out of 5', '2 out of 3', '4 out of 7', '1'],
    ['What is a "penalty kick" in soccer?', 'Free kick from the penalty spot', 'Corner kick', 'Goal kick', 'Throw-in'],
    ['How long is a soccer match?', '90 minutes', '60 minutes', '120 minutes', '45 minutes'],
    ['What is a "hat-trick" in soccer?', '3 goals by one player in a match', '3 assists', '3 saves', '3 fouls'],
    ['What colour card means a player is sent off?', 'Red', 'Yellow', 'Green', 'Blue'],
    ['What colour card is a warning in soccer?', 'Yellow', 'Red', 'White', 'Blue'],
    ['What does FIFA stand for?', 'International Federation of Association Football', 'Football In Free Association', 'First International Football Awards', 'Federal Institute For Athletics'],
    ['What sport is LeBron James known for?', 'Basketball', 'Football', 'Baseball', 'Soccer'],
    ['What does "MMA" stand for?', 'Mixed Martial Arts', 'Modern Martial Arts', 'Multiple Martial Arts', 'Major Martial Arts'],
    ['How many quarters in a basketball game?', '4', '2', '3', '6'],
    ['What is "offside" in soccer?', 'Player ahead of last defender', 'Out of bounds', 'Handball', 'Foul play'],
    ['What surface is Wimbledon tennis played on?', 'Grass', 'Clay', 'Hard court', 'Carpet'],
    ['Where is Wimbledon held?', 'London, England', 'Paris, France', 'New York, USA', 'Melbourne, Australia'],
    ['What sport uses the term "ace"?', 'Tennis', 'Soccer', 'Swimming', 'Boxing'],
    ['In which weight class did Muhammad Ali box?', 'Heavyweight', 'Middleweight', 'Lightweight', 'Welterweight'],
    ['Which country dominated world squash for decades?', 'Pakistan', 'Egypt', 'England', 'Australia'],
    ['How many points is a 3-pointer in basketball?', '3', '2', '1', '4'],
    ['What sport is the "Tour de France" part of?', 'Cycling', 'Running', 'Swimming', 'Driving'],
    ['What sport uses a "shuttlecock"?', 'Badminton', 'Tennis', 'Squash', 'Table tennis'],
    ['How many wrestlers compete in a WWE Royal Rumble match?', '30', '20', '40', '25'],
    ['In kabaddi, what must the raider keep doing while in the other half?', 'Chanting "kabaddi"', 'Clapping', 'Running in circles', 'Holding breath silently'],
    ['What sport does Lionel Messi play?', 'Soccer/Football', 'Basketball', 'Tennis', 'Baseball'],
    ['Which country did Messi play for?', 'Argentina', 'Brazil', 'Spain', 'Portugal'],
    ['What sport is Tiger Woods famous for?', 'Golf', 'Tennis', 'Cricket', 'Swimming'],
    ['What is a "free throw" in basketball?', 'Uncontested shot from the line', 'Pass to teammate', 'Dribbling', 'A block'],
    ['What is a "corner kick" in soccer?', 'Kick from the corner arc', 'Centre kick', 'Penalty kick', 'Goal kick'],
    ['What colour is a basketball?', 'Orange', 'White', 'Brown', 'Red'],
    ['How many teams play in the English Premier League?', '20', '18', '16', '22'],
    ['Which country dominates table tennis?', 'China', 'Japan', 'Sweden', 'Germany'],
    ['What is the famous Saturday night hockey show in Canada called?', 'Hockey Night in Canada', 'Canadian Hockey League', 'Saturday Night Hockey', 'The Hockey Show'],
    ['What is a "knockout" in boxing?', 'When a fighter cannot get up before a count of 10', 'A lucky punch', 'The first punch', 'A disqualification'],
    ['What does the referee blow to stop play?', 'Whistle', 'Horn', 'Bell', 'Drum'],
    ['Which La Liga club plays in all-white kit?', 'Real Madrid', 'Barcelona', 'Atletico Madrid', 'Sevilla'],
    ['What is Stone Cold Steve Austin\'s famous finishing move?', 'Stone Cold Stunner', 'RKO', 'Chokeslam', 'Pedigree'],
    ['How many rounds are in a standard championship boxing match?', '12', '10', '15', '8'],
    ['In what year did the Toronto Raptors win the NBA Championship?', '2019', '2018', '2020', '2017'],
  ],
  3: [
    ['In what year were the first modern Olympics held?', '1896', '1900', '1888', '1912'],
    ['Where were the first modern Olympics held?', 'Athens, Greece', 'Paris, France', 'London, England', 'Rome, Italy'],
    ['What is Formula 1?', 'Top-level car racing series', 'Running event', 'Swimming event', 'Cycling race'],
    ['How many Grand Slam tennis tournaments are there?', '4', '3', '5', '6'],
    ['Name the four Grand Slam tennis events.', 'Australian, French, Wimbledon, US Open', 'Wimbledon, French, Indian Wells, US Open', 'Australian, French, Italian, US Open', 'Wimbledon, Rogers, French, US Open'],
    ['What surface is the French Open played on?', 'Clay', 'Grass', 'Hard court', 'Carpet'],
    ['What surface is the US Open played on?', 'Hard court', 'Grass', 'Clay', 'Carpet'],
    ['What surface is the Australian Open played on?', 'Hard court', 'Clay', 'Grass', 'Carpet'],
    ['What country hosts the Tour de France?', 'France', 'Italy', 'Spain', 'Belgium'],
    ['How long is a marathon in kilometres?', '42.195 km', '40 km', '50 km', '36 km'],
    ['How many Olympic gold medals has Pakistan won in hockey?', '3', '2', '4', '1'],
    ['Who is considered the greatest Pakistani squash player ever?', 'Jahangir Khan', 'Jansher Khan', 'Qamar Zaman', 'Hashim Khan'],
    ['Which WWE superstar had a famous undefeated WrestleMania streak?', 'The Undertaker', 'John Cena', 'Triple H', 'Shawn Michaels'],
    ['Which football club is nicknamed "The Gunners"?', 'Arsenal', 'Chelsea', 'Liverpool', 'Tottenham'],
    ['What was Mike Tyson famous for in boxing?', 'Youngest ever heavyweight champion', 'Longest reign as champion', 'Most knockouts in history', 'Undefeated career'],
    ['What country hosted the 2016 Summer Olympics?', 'Brazil', 'China', 'UK', 'Japan'],
    ['In which city were the 2016 Olympics held?', 'Rio de Janeiro', 'Sao Paulo', 'Beijing', 'Tokyo'],
    ['What is a "grand slam" in tennis?', 'Winning all four major tournaments in one year', 'Winning one tournament', 'Playing in all events', 'A powerful serve'],
    ['What does "UFC" stand for?', 'Ultimate Fighting Championship', 'United Fighting Club', 'Universal Fight Challenge', 'Ultra Fight Championship'],
    ['What martial art is used most in MMA?', 'Mixed styles', 'Only karate', 'Only boxing', 'Only wrestling'],
    ['Which WWE superstar\'s finishing move is called the "RKO"?', 'Randy Orton', 'John Cena', 'The Rock', 'Batista'],
    ['Which F1 circuit is known as "The Temple of Speed"?', 'Monza', 'Silverstone', 'Monaco', 'Spa'],
    ['What Brazilian martial art is commonly used in MMA?', 'Brazilian Jiu-Jitsu', 'Capoeira', 'Muay Thai', 'Judo'],
    ['How many Grand Slam titles did Roger Federer win?', '20', '22', '18', '14'],
    ['What sport did Michael Jordan play?', 'Basketball', 'Baseball', 'Football', 'Golf'],
    ['Which NBA team did Michael Jordan play for?', 'Chicago Bulls', 'LA Lakers', 'Boston Celtics', 'Miami Heat'],
    ['What country did Pelé play soccer for?', 'Brazil', 'Argentina', 'Portugal', 'Spain'],
    ['How many FIFA World Cups has Brazil won?', '5', '4', '6', '3'],
    ['Which footballer has won the most Ballon d\'Or awards?', 'Lionel Messi', 'Cristiano Ronaldo', 'Michel Platini', 'Johan Cruyff'],
    ['How many Hockey World Cup titles has Pakistan won?', '4', '3', '5', '2'],
    ['Which player hit the famous bouncing buzzer-beater to eliminate Philadelphia in the 2019 NBA Playoffs?', 'Kawhi Leonard', 'Kyle Lowry', 'Pascal Siakam', 'Fred VanVleet'],
    ['How high is a basketball hoop from the ground?', '10 feet', '8 feet', '12 feet', '9 feet'],
    ['What is The Rock\'s finishing move called in WWE?', 'Rock Bottom', 'Stone Cold Stunner', 'RKO', 'Chokeslam'],
    ['In kabaddi, what is the player who crosses to the opposing side called?', 'Raider', 'Striker', 'Attacker', 'Chaser'],
    ['What is "par" in golf?', 'Expected number of strokes for a hole', 'Bonus point', 'Penalty', 'Extra round'],
    ['What is the "undercard" in a boxing event?', 'Fights before the main event', 'The final round', 'Training before the fight', 'Post-fight interview'],
    ['Which country hosted the 2022 FIFA World Cup?', 'Qatar', 'Russia', 'Brazil', 'South Africa'],
    ['Who won the 2022 FIFA World Cup?', 'Argentina', 'France', 'Brazil', 'Germany'],
    ['What sport uses a "putter"?', 'Golf', 'Tennis', 'Hockey', 'Cricket'],
    ['What does "EPL" stand for?', 'English Premier League', 'European Players League', 'Elite Pro League', 'English Pro League'],
    ['What is the "Ballon d\'Or"?', 'Award for best soccer player', 'Golden ball used in finals', 'Trophy shape', 'Stadium name'],
    ['What is a "slam dunk" in basketball?', 'Jumping and putting ball directly in hoop', 'Three-point shot', 'Free throw', 'Layup'],
    ['Which club did Ronaldo move to from Real Madrid in 2018?', 'Juventus', 'Manchester United', 'PSG', 'Bayern Munich'],
    ['What is the WWE "Attitude Era" known for?', 'Edgy content in the late 1990s', 'Family-friendly shows', 'Olympic-style wrestling', 'Women-only matches'],
    ['What is a "love" score in tennis?', 'Zero points', 'Winning point', '15 points', '40 points'],
    ['What is "deuce" in tennis?', 'Score is tied at 40-40', 'Game over', 'Set point', 'Match point'],
    ['What does "advantage" mean in tennis?', 'Player needs one more point to win after deuce', 'Leading by two games', 'First serve won', 'Break point'],
    ['What is the "UEFA Champions League"?', 'Top European club soccer tournament', 'World Cup', 'Olympics soccer', 'Youth league'],
    ['Which F1 team is based in Maranello, Italy?', 'Ferrari', 'McLaren', 'Mercedes', 'Red Bull'],
    ['What colour are Ferrari F1 cars traditionally?', 'Red', 'Blue', 'Silver', 'Green'],
  ],
  4: [
    ['Who has won the most F1 World Championships?', 'Lewis Hamilton / Michael Schumacher', 'Ayrton Senna', 'Sebastian Vettel', 'Alain Prost'],
    ['How many F1 titles did Schumacher win?', '7', '5', '6', '8'],
    ['Which F1 team has the most Constructors titles?', 'Ferrari', 'Mercedes', 'McLaren', 'Williams'],
    ['Which Toronto Raptor won the NBA Slam Dunk Contest in 2000?', 'Vince Carter', 'Tracy McGrady', 'Chris Bosh', 'DeMar DeRozan'],
    ['How many gold medals did Usain Bolt win at Olympics?', '8', '6', '9', '10'],
    ['What is Usain Bolt\'s 100m world record time?', '9.58 seconds', '9.69 seconds', '9.72 seconds', '9.50 seconds'],
    ['In which year did Bolt set the 100m record?', '2009', '2008', '2012', '2011'],
    ['In which year did Pakistan first win Olympic gold in hockey?', '1960', '1964', '1956', '1968'],
    ['How many consecutive WrestleMania matches did The Undertaker win?', '21', '18', '25', '15'],
    ['How many Olympic golds has Michael Phelps won?', '23', '18', '28', '15'],
    ['Which country has won the most Olympic gold medals overall?', 'United States', 'China', 'Russia', 'Great Britain'],
    ['What is "match point" in tennis?', 'One point away from winning the match', 'First point', 'Tie break', 'Final game'],
    ['Who has won the most Wimbledon singles titles (men)?', 'Roger Federer', 'Novak Djokovic', 'Pete Sampras', 'Rafael Nadal'],
    ['How many Wimbledon titles has Federer won?', '8', '7', '6', '9'],
    ['Who holds the record for most Grand Slams (men)?', 'Novak Djokovic', 'Roger Federer', 'Rafael Nadal', 'Pete Sampras'],
    ['Who broke The Undertaker\'s WrestleMania streak?', 'Brock Lesnar', 'John Cena', 'Triple H', 'The Rock'],
    ['What finishing move is Triple H famous for in WWE?', 'Pedigree', 'Stunner', 'RKO', 'Tombstone'],
    ['How many world records has Usain Bolt set?', '3 (100m, 200m, 4x100m relay)', '5', '2', '7'],
    ['What is a "double fault" in tennis?', 'Both serves fail', 'Two fouls', 'Missing a volley', 'Out of bounds twice'],
    ['Which F1 driver was known as "The Professor"?', 'Alain Prost', 'Ayrton Senna', 'Niki Lauda', 'Nelson Piquet'],
    ['What does "seeded" mean in a tournament?', 'Ranked and placed in the draw', 'New player', 'Wild card entry', 'Champion'],
    ['Which boxer famously bit Evander Holyfield\'s ear?', 'Mike Tyson', 'Lennox Lewis', 'Muhammad Ali', 'George Foreman'],
    ['How many World Open titles did Pakistani squash player Jansher Khan win?', '8', '6', '10', '5'],
    ['Who has scored the most goals in FIFA World Cup history?', 'Miroslav Klose', 'Ronaldo (Brazil)', 'Pelé', 'Just Fontaine'],
    ['How many World Cup goals did Klose score?', '16', '15', '14', '18'],
    ['What is a "grand prix" in F1?', 'Individual race in the F1 season', 'Championship final', 'Practice session', 'Qualifying round'],
    ['Which team won the first-ever Premier League title in 1992-93?', 'Manchester United', 'Arsenal', 'Liverpool', 'Blackburn'],
    ['What does "ground and pound" mean in MMA?', 'Striking a downed opponent', 'Wrestling on the ground', 'Kicking technique', 'Running at an opponent'],
    ['How many laps is the Monaco Grand Prix?', '78', '50', '72', '60'],
    ['What makes the Monaco GP special?', 'Street circuit through Monte Carlo', 'Longest track', 'Most corners', 'Night race'],
    ['What is "Hell in a Cell" in WWE?', 'A match inside a roofed steel cage', 'A tag team match', 'A ladder match', 'A battle royal'],
    ['What is the "sweet science" a nickname for?', 'Boxing', 'Fencing', 'Chess', 'Wrestling'],
    ['What is "La Liga"?', 'Spanish top soccer league', 'Italian league', 'French league', 'German league'],
    ['What is "Serie A"?', 'Italian top soccer league', 'Spanish league', 'French league', 'German league'],
    ['What is the "Bundesliga"?', 'German top soccer league', 'Austrian league', 'Swiss league', 'Dutch league'],
    ['Which soccer club is known as "The Red Devils"?', 'Manchester United', 'Liverpool', 'Arsenal', 'Chelsea'],
    ['Which soccer club plays at the Santiago Bernabéu?', 'Real Madrid', 'Barcelona', 'Atletico Madrid', 'Valencia'],
    ['Which soccer club plays at Camp Nou?', 'Barcelona', 'Real Madrid', 'Sevilla', 'Villarreal'],
    ['Which Pakistani hockey player was nicknamed "Maradona of Hockey"?', 'Shahbaz Ahmed', 'Hassan Sardar', 'Samiullah Khan', 'Islahuddin Siddiqui'],
    ['How many players are on a kabaddi team on the court?', '7', '5', '9', '11'],
    ['Which F1 team did Ayrton Senna famously drive for?', 'McLaren', 'Ferrari', 'Williams', 'Lotus'],
    ['What sport is Cristiano Ronaldo famous for?', 'Soccer/Football', 'Basketball', 'Tennis', 'Swimming'],
    ['Which country is Ronaldo from?', 'Portugal', 'Brazil', 'Spain', 'Argentina'],
    ['Which country is Neymar from?', 'Brazil', 'Argentina', 'Portugal', 'Colombia'],
    ['What is "VAR" in soccer?', 'Video Assistant Referee', 'Visual Audio Review', 'Virtual Aid Referee', 'Video Analysis Replay'],
    ['What is an "own goal" in soccer?', 'Scoring in your own team\'s net', 'Assisted goal', 'Penalty goal', 'Header goal'],
    ['Which footballer scored a hat-trick in the 2022 World Cup final?', 'Kylian Mbappé', 'Lionel Messi', 'Olivier Giroud', 'Antoine Griezmann'],
    ['How many consecutive squash matches did Jahangir Khan win?', '555', '400', '300', '600'],
    ['Which F1 circuit features the famous "Eau Rouge" corner?', 'Spa-Francorchamps', 'Monza', 'Silverstone', 'Monaco'],
    ['Which Canadian hockey player is nicknamed "Sid the Kid"?', 'Sidney Crosby', 'Wayne Gretzky', 'Connor McDavid', 'Mario Lemieux'],
  ],
  5: [
    ['What is the fastest 200m time ever recorded?', '19.19 seconds by Usain Bolt', '19.32 seconds', '19.50 seconds', '19.72 seconds'],
    ['In which city did Bolt run 9.58 in the 100m?', 'Berlin', 'Beijing', 'London', 'Rio'],
    ['Who holds the women\'s 100m world record?', 'Florence Griffith-Joyner', 'Shelly-Ann Fraser-Pryce', 'Elaine Thompson', 'Marion Jones'],
    ['Who was named Finals MVP when the Toronto Raptors won the 2019 NBA Championship?', 'Kawhi Leonard', 'Kyle Lowry', 'Pascal Siakam', 'Marc Gasol'],
    ['At what age did Jahangir Khan become the youngest World Open squash champion?', '17', '19', '21', '15'],
    ['In which year did Pakistan win their last Hockey World Cup?', '1994', '1990', '1986', '1998'],
    ['Which WrestleMania main event is often called the greatest: Stone Cold vs who?', 'The Rock', 'Shawn Michaels', 'The Undertaker', 'Triple H'],
    ['In what year did Brock Lesnar end The Undertaker\'s WrestleMania streak?', '2014', '2012', '2016', '2010'],
    ['Which F1 driver won 4 consecutive World Championships from 2010-2013?', 'Sebastian Vettel', 'Lewis Hamilton', 'Fernando Alonso', 'Michael Schumacher'],
    ['What is the record for most goals in a soccer World Cup?', '13 by Just Fontaine in 1958', '10 by Pelé', '12 by Gerd Muller', '11 by Ronaldo'],
    ['What is the fastest F1 pit stop ever?', 'Under 2 seconds', '3 seconds', '5 seconds', '4 seconds'],
    ['Which F1 team holds the fastest pit stop record?', 'Red Bull Racing', 'Mercedes', 'Ferrari', 'McLaren'],
    ['Which boxer retired undefeated with a 50-0 record?', 'Floyd Mayweather Jr.', 'Muhammad Ali', 'Rocky Marciano', 'Manny Pacquiao'],
    ['Which club has won the most Premier League titles?', 'Manchester United', 'Liverpool', 'Arsenal', 'Chelsea'],
    ['How many Premier League titles has Manchester United won?', '13', '11', '15', '9'],
    ['Who is the fastest woman in Olympic 100m history?', 'Elaine Thompson-Herah', 'Florence Griffith-Joyner', 'Shelly-Ann Fraser-Pryce', 'Dina Asher-Smith'],
    ['Which WWE match type features ladders, tables, and chairs?', 'TLC match', 'Steel cage match', 'Iron man match', 'Last man standing'],
    ['Which UFC lightweight champion retired undefeated at 29-0?', 'Khabib Nurmagomedov', 'Conor McGregor', 'Tony Ferguson', 'Charles Oliveira'],
    ['Who was the first boxer to win the heavyweight title three separate times?', 'Muhammad Ali', 'Evander Holyfield', 'Lennox Lewis', 'Mike Tyson'],
    ['Which country has hosted the most Olympic Games?', 'United States', 'United Kingdom', 'France', 'Greece'],
    ['Which Pakistani squash player succeeded Jahangir Khan as World No. 1?', 'Jansher Khan', 'Qamar Zaman', 'Hashim Khan', 'Roshan Khan'],
    ['Which F1 driver has the most race wins in history?', 'Lewis Hamilton', 'Michael Schumacher', 'Sebastian Vettel', 'Alain Prost'],
    ['What does "photo finish" mean?', 'Race decided by a photograph at finish line', 'Taking team photos', 'Photography competition', 'Celebration photo'],
    ['Who has the most Premier League goals?', 'Alan Shearer', 'Wayne Rooney', 'Thierry Henry', 'Sergio Aguero'],
    ['How many EPL goals did Alan Shearer score?', '260', '230', '280', '210'],
    ['Whose catchphrase is "If ya smell what The Rock is cookin\'"?', 'The Rock', 'Stone Cold', 'John Cena', 'The Undertaker'],
    ['What sport did Muhammad Ali compete in?', 'Boxing', 'Wrestling', 'MMA', 'Judo'],
    ['What was Muhammad Ali\'s famous catchphrase?', 'Float like a butterfly, sting like a bee', 'I am the best', 'Just do it', 'Victory is mine'],
    ['What is the highest possible break in snooker?', '147', '155', '140', '130'],
    ['What is the "Davis Cup" for?', 'International men\'s tennis team event', 'Soccer trophy', 'Golf cup', 'Swimming relay'],
    ['Who has the most Champions League titles (club)?', 'Real Madrid', 'AC Milan', 'Liverpool', 'Barcelona'],
    ['How many Champions League titles has Real Madrid won?', '15', '13', '12', '10'],
    ['What is "doping" in sports?', 'Using banned substances to enhance performance', 'Training method', 'Diet plan', 'Recovery technique'],
    ['What organization conducts anti-doping tests?', 'WADA (World Anti-Doping Agency)', 'FIFA', 'IOC', 'WHO'],
    ['What is the "Olympic Village"?', 'Housing complex for athletes', 'Tourist area', 'Stadium name', 'Training center'],
    ['Who did Muhammad Ali fight in "The Rumble in the Jungle"?', 'George Foreman', 'Joe Frazier', 'Sonny Liston', 'Leon Spinks'],
    ['How many weight classes are in Olympic boxing?', '13', '10', '8', '15'],
    ['What is the "Commonwealth Games"?', 'Multi-sport event for Commonwealth nations', 'British Olympics', 'European Games', 'Asian Games'],
    ['How often are the Commonwealth Games held?', 'Every 4 years', 'Every 2 years', 'Every year', 'Every 5 years'],
    ['Which footballer has scored the most Champions League goals ever?', 'Cristiano Ronaldo', 'Lionel Messi', 'Raul', 'Robert Lewandowski'],
    ['Which country did Conor McGregor represent in the UFC?', 'Ireland', 'England', 'Scotland', 'USA'],
    ['What is "sudden death" in sports?', 'First to score wins in overtime', 'Last play of game', 'Penalty shootout', 'Fastest finish'],
    ['How long was Jahangir Khan\'s unbeaten run in squash?', 'Over 5 years (1981-1986)', '3 years', '7 years', '2 years'],
    ['Which club won the 2022-23 treble: Premier League, FA Cup, and Champions League?', 'Manchester City', 'Liverpool', 'Real Madrid', 'Chelsea'],
    ['Which Grand Slam has Rafael Nadal won most?', 'French Open', 'US Open', 'Wimbledon', 'Australian Open'],
    ['How many French Open titles did Nadal win?', '14', '12', '10', '8'],
    ['What is "esports"?', 'Competitive video gaming', 'Electronic sprinting', 'Online fitness', 'Virtual reality sport'],
    ['What was the "Fight of the Century" boxing match in 1971?', 'Muhammad Ali vs Joe Frazier', 'Ali vs Foreman', 'Tyson vs Holyfield', 'Lewis vs Tyson'],
    ['Which F1 team did Max Verstappen win his first championship with?', 'Red Bull Racing', 'Mercedes', 'Ferrari', 'McLaren'],
    ['Which Pakistani was the first-ever British Open squash champion?', 'Hashim Khan', 'Jahangir Khan', 'Roshan Khan', 'Azam Khan'],
  ],
  6: [
    ['What is the "offside rule" in soccer in detail?', 'Player behind last defender when ball is played', 'Near the goal', 'Past halfway', 'In the box'],
    ['When was the offside rule introduced in soccer?', '1863 (modified in 1925)', '1900', '1950', '1870'],
    ['What is "tiki-taka" in soccer?', 'Short passing possession style (Barcelona)', 'Long ball tactics', 'Defensive strategy', 'Counter-attacking'],
    ['Which coach popularized tiki-taka?', 'Pep Guardiola', 'Jose Mourinho', 'Jurgen Klopp', 'Carlo Ancelotti'],
    ['What is the "DRS" in Formula 1?', 'Drag Reduction System', 'Driver Radio Signal', 'Data Review System', 'Dynamic Racing Speed'],
    ['What does the DRS do in F1?', 'Opens rear wing flap to reduce drag', 'Boosts engine power', 'Activates brakes', 'Changes tyre grip'],
    ['What is a "safety car" in F1?', 'Car that leads pack during hazardous conditions', 'Backup race car', 'Medical car', 'Pace car for warm-up only'],
    ['What fuel do F1 cars use (2026 regs)?', 'Sustainable fuel blend', 'Regular petrol', 'Diesel', 'Pure electric'],
    ['What is the "ATP ranking" in tennis?', 'Association of Tennis Professionals ranking', 'All Tennis Players rank', 'Annual Tennis Points', 'Advanced Tennis Placing'],
    ['What is the "WTA" in tennis?', 'Women\'s Tennis Association', 'World Tennis Awards', 'Winning Tennis Athletes', 'Women\'s Training Academy'],
    ['Which Pakistani squash family produced multiple world champions across generations?', 'The Khan family (Hashim, Roshan, Jahangir, Jansher)', 'The Ahmed family', 'The Malik family', 'The Hussain family'],
    ['What is "kayfabe" in professional wrestling?', 'Maintaining the illusion that wrestling storylines are real', 'A finishing move', 'A tag team formation', 'A type of wrestling ring'],
    ['What is "VO2 max"?', 'Maximum oxygen uptake during exercise', 'Heart rate at rest', 'Lung capacity', 'Blood pressure measure'],
    ['What does a high VO2 max indicate?', 'Better aerobic fitness', 'Stronger muscles', 'Better flexibility', 'More speed'],
    ['What is "lactate threshold"?', 'Point where lactic acid builds faster than cleared', 'Maximum speed', 'Heart rate at rest', 'Warm-up point'],
    ['What is the "Fosbury Flop"?', 'High jump technique going back-first', 'Long jump style', 'Pole vault move', 'Diving technique'],
    ['Who invented the Fosbury Flop?', 'Dick Fosbury', 'Carl Lewis', 'Jesse Owens', 'Bob Beamon'],
    ['In what year did Fosbury debut his technique?', '1968 Olympics', '1972 Olympics', '1964 Olympics', '1976 Olympics'],
    ['In which decade did Pakistan dominate both Olympic and World Cup hockey?', '1960s-1980s', '1940s-1960s', '1980s-2000s', '1990s-2010s'],
    ['What boxing technique did Muhammad Ali call "rope-a-dope"?', 'Leaning on ropes to tire the opponent', 'A fast jab combination', 'A defensive footwork pattern', 'A way to dodge punches'],
    ['What is the "golden goal" rule?', 'First goal in extra time wins (now discontinued)', 'Goal with header', 'Penalty goal', 'Own goal counts double'],
    ['Why was the golden goal rule removed?', 'Teams played too defensively', 'Too exciting', 'Hard to officiate', 'Players complained'],
    ['What replaced golden goal in soccer?', 'Full extra time then penalties', 'Immediate penalties', 'Coin toss', 'Replay match'],
    ['What is "altitude training"?', 'Training at high elevation to boost red blood cells', 'Training on airplanes', 'High-jump training', 'Mountain climbing'],
    ['Why do athletes train at altitude?', 'Body produces more red blood cells', 'Better weather', 'Fewer distractions', 'Cheaper facilities'],
    ['What is the "biological passport" in anti-doping?', 'Tracking athlete blood values over time', 'Travel document', 'Medical certificate', 'ID card'],
    ['What is "blood doping"?', 'Increasing red blood cells artificially', 'Drug injection', 'Diet supplement', 'Blood donation'],
    ['What is a "rear naked choke" in MMA?', 'A submission hold applied from behind the opponent', 'A takedown move', 'A striking technique', 'A cage clinch'],
    ['What is the minimum weight of an F1 car with driver (approx)?', 'Around 800 kg', 'Around 500 kg', 'Around 1200 kg', 'Around 300 kg'],
    ['What is "progressive overload"?', 'Gradually increasing training demands', 'Immediate max effort', 'Reducing training', 'Constant same routine'],
    ['What is the "Montreal Screwjob" in WWE history?', 'Controversial 1997 finish where Vince McMahon changed the match result', 'A famous ladder match', 'A tag team betrayal', 'An injury angle'],
    ['What is "expected goals" (xG) in football analytics?', 'Statistical measure of chance quality based on shot data', 'Goals scored per game', 'Predicted final score', 'Average goals in a league'],
    ['What is a "PB" in athletics?', 'Personal Best', 'Professional Best', 'Point Bonus', 'Performance Badge'],
    ['What is "SB" in athletics results?', 'Season\'s Best', 'Silver Best', 'Special Best', 'Super Best'],
    ['What role did Islahuddin Siddiqui play in Pakistan hockey history?', 'Star forward and all-time leading goal scorer', 'Goalkeeper who never conceded', 'First Pakistani hockey captain', 'Coached Pakistan to World Cup'],
    ['What is "cryotherapy" used for in sport?', 'Cold treatment for recovery', 'Heat therapy', 'Massage type', 'Stretching routine'],
    ['What temperature is a cryotherapy chamber?', 'Around -110°C to -140°C', '-50°C', '-10°C', '-200°C'],
    ['What is the "hamstring" muscle group?', 'Muscles at back of thigh', 'Front of thigh', 'Calf muscles', 'Shin muscles'],
    ['What is an "ACL" injury?', 'Anterior Cruciate Ligament tear in knee', 'Ankle injury', 'Arm injury', 'Back injury'],
    ['Why are ACL injuries common in soccer?', 'Sudden direction changes stress the knee', 'Too much running', 'Ball impact', 'Poor shoes'],
    ['What is "interval training"?', 'Alternating high and low intensity exercise', 'Constant pace training', 'Stretching only', 'Weights only'],
    ['What is "HIIT"?', 'High-Intensity Interval Training', 'Heavy Impact Individual Training', 'Hard Interval Indoor Training', 'High Incline Intense Training'],
    ['What is the "anaerobic threshold"?', 'Exercise intensity where anaerobic metabolism dominates', 'Maximum heart rate', 'Resting state', 'Recovery point'],
    ['What is a "compound movement" in training?', 'Exercise using multiple joints and muscles', 'Single muscle exercise', 'Stretching', 'Cardio only'],
    ['What is "concentric contraction"?', 'Muscle shortens while generating force', 'Muscle lengthens', 'Muscle stays same length', 'No muscle movement'],
    ['What is "eccentric contraction"?', 'Muscle lengthens while under tension', 'Muscle shortens', 'Muscle stays same', 'No contraction'],
    ['What is the "Valsalva maneuver" in lifting?', 'Holding breath to stabilize core', 'Exhaling loudly', 'Counting reps', 'Stretching technique'],
    ['What is "RPE" in exercise science?', 'Rate of Perceived Exertion', 'Running Pace Estimate', 'Recovery Period End', 'Resting Pulse Evaluation'],
    ['What does the "RICE" method stand for?', 'Rest, Ice, Compression, Elevation', 'Run, Ice, Cool, Eat', 'Rest, Inject, Compress, Exercise', 'Recovery, Ice, Care, Elevate'],
    ['What is a "guillotine choke" in MMA?', 'A front headlock submission targeting the neck', 'A leg lock', 'An arm bar variation', 'A striking combination'],
  ],
};

export { popCultureSexEd } from './popCultureToronto';

