/** Generic Urdu / Roman-Urdu “boys’ banter” lines — no names, host-only wrong button. Grades 4–6 informal mode. */

const ROASTS: string[] = [
  'Abay ye tou theek ker le, dukkan!',
  'Arrey bhai, dimagh ghar pe chhor aaya tha?',
  'Itna easy tha — yeh to bachon wala sawal tha!',
  'Chal chal, zyada hero mat ban.',
  'Ajeeb scene hai — yeh bhi galat?',
  'Ammi ko pata chal gaya to kya hoga socha hai?',
  'Thori si mehnat kar le, setting lag rahi hai.',
  'Yeh answer tou notes mein likha tha na?',
  'Haw haye! Dosto ke saamne kya kar diya?',
  'Dekh kar click kar — aankhein decoration ke liye hain?',
  'Aisa galat? Matlab dil se nahi padha.',
  'Chalo koi nahi, agla round mein sudhar jana.',
  'Itna confidence, phir bhi tick galat?',
  'Lagta hai neend poori nahi hui.',
  'Aaj brain ka day off hai?',
  'Yeh tou ghalat fehmi ka shikaar ho gaye.',
  'Thora focus — yeh easy pickings thi.',
  'Boss, yeh tou common sense tha.',
  'Kya scene hai yaar, yeh bhi miss?',
  'Aise kaise? Padhai ka waqt nahi mila?',
  'Relax kar, lekin answer tou sahi hota.',
  'Dosto ne hasna shuru kar diya hoga.',
  'Ajeeb kismet — itna seedha sawal.',
  'Dimagh ka dahi mat bana, simple tha.',
  'Lagta hai mind elsewhere hai — wapas aao.',
  'Yeh tou ghalat fehmi nahi, seedha ghalat hai.',
  'Thora sa soch lete tou set tha.',
  'Kya baat hai, pressure mein slip?',
  'Aisa galat? Matlab practice ki zaroorat hai.',
  'Chalo koi nahi — agla chance pakka.',
  'Aankh band karke bhi sahi lag sakta tha.',
  'Yeh tou basic tha — refresh karo apna.',
  'Scene on hai lekin answer off hai.',
  'Ajeeb — yeh tou guess bhi sahi ho jata.',
  'Thori si tension, zyada galat?',
  'Lagta hai luck bhi side le gayi.',
  'Ajeeb — yeh tou suna sunaya tha.',
  'Simple si baat — phir bhi miss?',
  'Aise kaise yaar, yeh tou clear tha.',
  'Chalo has lo — agla round tight karna.',
  'Dimaag ki batti jalao — yeh tou easy tha.',
  'Ajeeb — yeh tou first read mein pakka tha.',
  'Kya scene — yeh bhi slip ho gaya?',
  'Thora focus — warna team hasayegi.',
  'Boss, yeh tou common knowledge thi.',
  'Relax — lekin agla waqt tight karna.',
  'Ajeeb — yeh tou seedha tha.',
  'Aisa galat? Matlab revision time.',
  'Abay tu engineer banega? Pehle yeh tou theek kar.',
  'Oye hoye — itna seedha tha, phir bhi?',
  'Dimaag ka GPS off hai kya?',
  'Yaar yeh tou ghalat fehmi se bhi seedha tha.',
  'Chup chaap corner mein baith — agla try.',
  'Itni jaldi galat? Record toot gaya.',
  'Scene achha tha, answer barbaad.',
  'Bhai setting strong, output weak.',
  'Aisa lagta hai guess bhi ignore kar diya.',
  'Thora dimagh lagata tou scene set tha.',
  'Abay focus — yeh tou one-tap tha.',
  'Lagta hai padhai ka Wi‑Fi disconnect hai.',
  'Yeh miss? Team chat ab full roast mode.',
  'Ajeeb — yeh tou suna tha school mein.',
  'Confidence 100, accuracy 0 — kya combo hai.',
  'Chalo, agla question se comeback.',
];

export function pickRandomInformalRoast(): string {
  return ROASTS[Math.floor(Math.random() * ROASTS.length)] ?? ROASTS[0]!;
}
